name: "static analysis checker"
description: "static code analysis checker for golang"
author: "grandcolline"
inputs:
  run:
    description: "excute command. [errcheck/fmt/imports/lint/sec/shadow/staticcheck/vet]"
    required: true
  directory:
    description: "action wroking directory."
    default: "."
    required: false
  comment:
    description: "send comment to PR if true."
    default: true
    required: false
  token:
    description: "github token. this is require when comment is true."
    default: ""
    required: false
  flags:
    description: "add flags"
    default: ""
    required: false
  ignore-defer:
    description: "if this is true, do not detect 'defer' with error. This is only valid when run is errcheck."
    default: false
    required: false
  go-mod-gh-username:
    description: "github username for go dependencies from private repos. Must match the account token generated under"
    default: ""
    required: false
  go-mod-gh-token:
    description: "github personal access token for go dependencies from private repos. Must match username account"
    default: ""
    required: false
  go-mod-goprivate:
    description: "git private organization url. eg. github.com/my-org"
    default: ""
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.run }}
    - ${{ inputs.directory }}
    - ${{ inputs.comment }}
    - ${{ inputs.token }}
    - ${{ inputs.flags }}
    - ${{ inputs.ignore-defer }}
    - ${{ inputs.go-mod-gh-username }}
    - ${{ inputs.go-mod-gh-token }}
    - ${{ inputs.go-mod-goprivate }}
branding:
  icon: "alert-triangle"
  color: "yellow"
